export const POSITION_INITIAL = 'POSITION_INITIAL';
export const ADD_POSITION = 'ADD_POSITION';
export const DELETE_POSITION = 'DELETE_POSITION';
export const HISTORY_FILE_UPLOAD = 'HISTORY_FILE_UPLOAD';
export const POLICY_UPDATE = 'POLICY_UPDATE';
export const POLICY_SIGN_START = 'POLICY_SIGN_START';
export const POLICY_SIGN_SUCCESS = 'POLICY_SIGN_SUCCESS';
export const POLICY_SIGN_ERROR = 'POLICY_SIGN_ERROR';

