export const ADD_POSITION = 'ADD_POSITION';
export const DELETE_POSITION = 'DELETE_POSITION';
export const CREATE_POLICY = 'CREATE_POLICY';
export const POLICY_UPDATE = 'POLICY_UPDATE';
export const POLICY_SIGN_START = 'POLICY_SIGN_START';
export const POLICY_SIGN_SUCCESS = 'POLICY_SIGN_SUCCESS';
export const POLICY_SIGN_ERROR = 'POLICY_SIGN_ERROR';

