export const POLICY_GET = 'POLICY_GET';
export const POLICY_SMARTDEPOSIT_INFO_GET = 'POLICY_SMARTDEPOSIT_INFO_GET';
export const POOL_STATE_CHANGE = 'POOL_STATE_CHANGE';
export const WALLET_OPEN = 'WALLET_OPEN';

