export const POLICY_GET = 'POLICY_GET';
export const REVIEW_TASKS_GET = 'REVIEW_TASKS_GET';
export const REVIEW_TASK_GET = 'REVIEW_TASK_GET';
export const REVIEW_TASK_SIGN_START = 'REVIEW_TASK_SIGN_START';
export const REVIEW_TASK_SIGN_SUCCESS = 'REVIEW_TASK_SIGN_SUCCESS';
export const REVIEW_TASK_SIGN_ERROR = 'REVIEW_TASK_SIGN_ERROR';

export const POLICY_SMARTDEPOSIT_INFO_GET = 'POLICY_SMARTDEPOSIT_INFO_GET';
export const POOL_STATE_CHANGE = 'POOL_STATE_CHANGE';
export const WALLET_OPEN = 'WALLET_OPEN';
export const WALLET_NEW_GENERATE = 'WALLET_NEW_GENERATE';

